<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stealth-api-v2.0.proto

namespace Stealth;

/**
 * Gauge signal state for strategies (PCES lights). 
 *
 * Protobuf enum <code>Stealth\GaugeSignal</code>
 */
class GaugeSignal
{
    /**
     * Unknown signal (gauge signal not set - use default).
     *
     * Generated from protobuf enum <code>Unknown = 0;</code>
     */
    const Unknown = 0;
    /**
     * Signal to enter a short position.
     *
     * Generated from protobuf enum <code>Short = 1;</code>
     */
    const Short = 1;
    /**
     * No current signal.
     *
     * Generated from protobuf enum <code>Flat = 2;</code>
     */
    const Flat = 2;
    /**
     * Signal to enter a long position.
     *
     * Generated from protobuf enum <code>Long = 3;</code>
     */
    const Long = 3;
    /**
     * Dual signal (long or short - no specific direction).
     *
     * Generated from protobuf enum <code>Dual = 4;</code>
     */
    const Dual = 4;
}

