<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stealth-api-v2.0.proto

namespace Stealth;

/**
 * The type of instrument being traded. 
 *
 * Protobuf enum <code>Stealth\InstrumentType</code>
 */
class InstrumentType
{
    /**
     * Not a valid instrument.
     *
     * Generated from protobuf enum <code>NoInstrument = 0;</code>
     */
    const NoInstrument = 0;
    /**
     * Common stock.
     *
     * Generated from protobuf enum <code>CommonStock = 1;</code>
     */
    const CommonStock = 1;
    /**
     * Stock option.
     *
     * Generated from protobuf enum <code>StockOption = 2;</code>
     */
    const StockOption = 2;
    /**
     * Future.
     *
     * Generated from protobuf enum <code>Future = 3;</code>
     */
    const Future = 3;
    /**
     * Index.
     *
     * Generated from protobuf enum <code>Index = 4;</code>
     */
    const Index = 4;
    /**
     * Foreign Exchange (Currency).
     *
     * Generated from protobuf enum <code>ForexContract = 5;</code>
     */
    const ForexContract = 5;
    /**
     * Future option.
     *
     * Generated from protobuf enum <code>FutureOption = 6;</code>
     */
    const FutureOption = 6;
    /**
     * Future instrument (underlying).
     *
     * Generated from protobuf enum <code>FutureInstrument = 7;</code>
     */
    const FutureInstrument = 7;
    /**
     * Combo pairing.
     *
     * Generated from protobuf enum <code>Combo = 8;</code>
     */
    const Combo = 8;
    /**
     * Combo underlying.
     *
     * Generated from protobuf enum <code>ComboInstrument = 9;</code>
     */
    const ComboInstrument = 9;
    /**
     * Crypto Currency (Bitcoin, etc.)
     *
     * Generated from protobuf enum <code>CryptoCurrency = 10;</code>
     */
    const CryptoCurrency = 10;
}

