<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stealth-api-v2.0.proto

namespace Stealth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * MultiframeUpdate represents a new multi-timeframe equilibrium subscription update. 
 * Values should be converted to between -1 and 1 by dividing by 1000. 
 *
 * Generated from protobuf message <code>stealth.MultiframeUpdate</code>
 */
class MultiframeUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * The timestamp of the latest update.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     */
    private $timestamp = 0;
    /**
     * The 5 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_5 = 2;</code>
     */
    private $min_5 = 0;
    /**
     * The 10 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_10 = 3;</code>
     */
    private $min_10 = 0;
    /**
     * The 15 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_15 = 4;</code>
     */
    private $min_15 = 0;
    /**
     * The 30 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_30 = 5;</code>
     */
    private $min_30 = 0;
    /**
     * The 45 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_45 = 6;</code>
     */
    private $min_45 = 0;
    /**
     * The 60 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_60 = 7;</code>
     */
    private $min_60 = 0;
    /**
     * The 120 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_120 = 8;</code>
     */
    private $min_120 = 0;
    /**
     * The 180 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_180 = 9;</code>
     */
    private $min_180 = 0;
    /**
     * The 240 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_240 = 10;</code>
     */
    private $min_240 = 0;
    /**
     * The 1 day value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 day_1 = 11;</code>
     */
    private $day_1 = 0;
    /**
     * Is the data that generated this potentially dirty (or stale)?
     *
     * Generated from protobuf field <code>bool is_dirty = 12;</code>
     */
    private $is_dirty = false;

    public function __construct() {
        \GPBMetadata\StealthApiV20::initOnce();
        parent::__construct();
    }

    /**
     * The timestamp of the latest update.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @return int|string
     */
    public function getTimestamp()
    {
        return $this->timestamp;
    }

    /**
     * The timestamp of the latest update.
     *
     * Generated from protobuf field <code>uint64 timestamp = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setTimestamp($var)
    {
        GPBUtil::checkUint64($var);
        $this->timestamp = $var;

        return $this;
    }

    /**
     * The 5 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_5 = 2;</code>
     * @return int
     */
    public function getMin5()
    {
        return $this->min_5;
    }

    /**
     * The 5 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_5 = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setMin5($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_5 = $var;

        return $this;
    }

    /**
     * The 10 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_10 = 3;</code>
     * @return int
     */
    public function getMin10()
    {
        return $this->min_10;
    }

    /**
     * The 10 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_10 = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setMin10($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_10 = $var;

        return $this;
    }

    /**
     * The 15 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_15 = 4;</code>
     * @return int
     */
    public function getMin15()
    {
        return $this->min_15;
    }

    /**
     * The 15 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_15 = 4;</code>
     * @param int $var
     * @return $this
     */
    public function setMin15($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_15 = $var;

        return $this;
    }

    /**
     * The 30 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_30 = 5;</code>
     * @return int
     */
    public function getMin30()
    {
        return $this->min_30;
    }

    /**
     * The 30 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_30 = 5;</code>
     * @param int $var
     * @return $this
     */
    public function setMin30($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_30 = $var;

        return $this;
    }

    /**
     * The 45 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_45 = 6;</code>
     * @return int
     */
    public function getMin45()
    {
        return $this->min_45;
    }

    /**
     * The 45 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_45 = 6;</code>
     * @param int $var
     * @return $this
     */
    public function setMin45($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_45 = $var;

        return $this;
    }

    /**
     * The 60 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_60 = 7;</code>
     * @return int
     */
    public function getMin60()
    {
        return $this->min_60;
    }

    /**
     * The 60 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_60 = 7;</code>
     * @param int $var
     * @return $this
     */
    public function setMin60($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_60 = $var;

        return $this;
    }

    /**
     * The 120 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_120 = 8;</code>
     * @return int
     */
    public function getMin120()
    {
        return $this->min_120;
    }

    /**
     * The 120 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_120 = 8;</code>
     * @param int $var
     * @return $this
     */
    public function setMin120($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_120 = $var;

        return $this;
    }

    /**
     * The 180 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_180 = 9;</code>
     * @return int
     */
    public function getMin180()
    {
        return $this->min_180;
    }

    /**
     * The 180 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_180 = 9;</code>
     * @param int $var
     * @return $this
     */
    public function setMin180($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_180 = $var;

        return $this;
    }

    /**
     * The 240 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_240 = 10;</code>
     * @return int
     */
    public function getMin240()
    {
        return $this->min_240;
    }

    /**
     * The 240 minute value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 min_240 = 10;</code>
     * @param int $var
     * @return $this
     */
    public function setMin240($var)
    {
        GPBUtil::checkInt32($var);
        $this->min_240 = $var;

        return $this;
    }

    /**
     * The 1 day value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 day_1 = 11;</code>
     * @return int
     */
    public function getDay1()
    {
        return $this->day_1;
    }

    /**
     * The 1 day value. (-1000 to 1000)
     *
     * Generated from protobuf field <code>sint32 day_1 = 11;</code>
     * @param int $var
     * @return $this
     */
    public function setDay1($var)
    {
        GPBUtil::checkInt32($var);
        $this->day_1 = $var;

        return $this;
    }

    /**
     * Is the data that generated this potentially dirty (or stale)?
     *
     * Generated from protobuf field <code>bool is_dirty = 12;</code>
     * @return bool
     */
    public function getIsDirty()
    {
        return $this->is_dirty;
    }

    /**
     * Is the data that generated this potentially dirty (or stale)?
     *
     * Generated from protobuf field <code>bool is_dirty = 12;</code>
     * @param bool $var
     * @return $this
     */
    public function setIsDirty($var)
    {
        GPBUtil::checkBool($var);
        $this->is_dirty = $var;

        return $this;
    }

}

