<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stealth-api-v2.0.proto

namespace Stealth;

/**
 * Entry/Exit signal state for strategies. 
 *
 * Protobuf enum <code>Stealth\StrategySignal</code>
 */
class StrategySignal
{
    /**
     * No current signal.
     *
     * Generated from protobuf enum <code>None = 0;</code>
     */
    const None = 0;
    /**
     * Signal to enter a long position.
     *
     * Generated from protobuf enum <code>LongSignal = 1;</code>
     */
    const LongSignal = 1;
    /**
     * Signal to enter a short position.
     *
     * Generated from protobuf enum <code>ShortSignal = 2;</code>
     */
    const ShortSignal = 2;
}

