<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stealth-api-v2.0.proto

namespace Stealth;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Holds the results of a symbol search request within a symbol search subscription.
 * Note: The user must subscribe to a definition/search subscription to get results 
 *       and make specific requests using a definition/search/{term} send message. 
 *
 * Generated from protobuf message <code>stealth.SymbolSearchUpdate</code>
 */
class SymbolSearchUpdate extends \Google\Protobuf\Internal\Message
{
    /**
     * The search term the results are for.
     *
     * Generated from protobuf field <code>string search_term = 1;</code>
     */
    private $search_term = '';
    /**
     * The search results.
     *
     * Generated from protobuf field <code>repeated .stealth.SymbolSearchResult results = 2;</code>
     */
    private $results;

    public function __construct() {
        \GPBMetadata\StealthApiV20::initOnce();
        parent::__construct();
    }

    /**
     * The search term the results are for.
     *
     * Generated from protobuf field <code>string search_term = 1;</code>
     * @return string
     */
    public function getSearchTerm()
    {
        return $this->search_term;
    }

    /**
     * The search term the results are for.
     *
     * Generated from protobuf field <code>string search_term = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setSearchTerm($var)
    {
        GPBUtil::checkString($var, True);
        $this->search_term = $var;

        return $this;
    }

    /**
     * The search results.
     *
     * Generated from protobuf field <code>repeated .stealth.SymbolSearchResult results = 2;</code>
     * @return \Google\Protobuf\Internal\RepeatedField
     */
    public function getResults()
    {
        return $this->results;
    }

    /**
     * The search results.
     *
     * Generated from protobuf field <code>repeated .stealth.SymbolSearchResult results = 2;</code>
     * @param \Stealth\SymbolSearchResult[]|\Google\Protobuf\Internal\RepeatedField $var
     * @return $this
     */
    public function setResults($var)
    {
        $arr = GPBUtil::checkRepeatedField($var, \Google\Protobuf\Internal\GPBType::MESSAGE, \Stealth\SymbolSearchResult::class);
        $this->results = $arr;

        return $this;
    }

}

