<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The ConnectRequest message is used to connect to the server. This is the first 
 * message that must be sent to the server before any other requests are made.
 * Use within a RequestFrame. 
 *
 * Generated from protobuf message <code>stomp.ConnectRequest</code>
 */
class ConnectRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The proto-stomp versions the client can handle.
     *
     * Generated from protobuf field <code>string accept_version = 1;</code>
     */
    private $accept_version = '';
    /**
     * The username to log in with.
     *
     * Generated from protobuf field <code>string login = 2;</code>
     */
    private $login = '';
    /**
     * The password to log in with.
     *
     * Generated from protobuf field <code>string passcode = 3;</code>
     */
    private $passcode = '';
    /**
     * Additional server-specific information to include.
     *
     * Generated from protobuf field <code>bytes body = 4;</code>
     */
    private $body = '';

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * The proto-stomp versions the client can handle.
     *
     * Generated from protobuf field <code>string accept_version = 1;</code>
     * @return string
     */
    public function getAcceptVersion()
    {
        return $this->accept_version;
    }

    /**
     * The proto-stomp versions the client can handle.
     *
     * Generated from protobuf field <code>string accept_version = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setAcceptVersion($var)
    {
        GPBUtil::checkString($var, True);
        $this->accept_version = $var;

        return $this;
    }

    /**
     * The username to log in with.
     *
     * Generated from protobuf field <code>string login = 2;</code>
     * @return string
     */
    public function getLogin()
    {
        return $this->login;
    }

    /**
     * The username to log in with.
     *
     * Generated from protobuf field <code>string login = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setLogin($var)
    {
        GPBUtil::checkString($var, True);
        $this->login = $var;

        return $this;
    }

    /**
     * The password to log in with.
     *
     * Generated from protobuf field <code>string passcode = 3;</code>
     * @return string
     */
    public function getPasscode()
    {
        return $this->passcode;
    }

    /**
     * The password to log in with.
     *
     * Generated from protobuf field <code>string passcode = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setPasscode($var)
    {
        GPBUtil::checkString($var, True);
        $this->passcode = $var;

        return $this;
    }

    /**
     * Additional server-specific information to include.
     *
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * Additional server-specific information to include.
     *
     * Generated from protobuf field <code>bytes body = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

}

