<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The DisconnectRequest message is used to inform the server that a disconnection
 * is about to be made. Server implementations must be able to handle disconnections 
 * with and without this request. Use within a RequestFrame. 
 *
 * Generated from protobuf message <code>stomp.DisconnectRequest</code>
 */
class DisconnectRequest extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

}

