<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Heartbeat message for keep-alive purposes. 
 *
 * Generated from protobuf message <code>stomp.Heartbeat</code>
 */
class Heartbeat extends \Google\Protobuf\Internal\Message
{

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

}

