<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notifies the client that a request has been fully processed. Sent in response to any 
 * message sent to the server with a receipt id included. 
 *
 * Generated from protobuf message <code>stomp.ReceiptResponse</code>
 */
class ReceiptResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The receipt identifier included in the request.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 1;</code>
     */
    private $receipt_id = 0;

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * The receipt identifier included in the request.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 1;</code>
     * @return int|string
     */
    public function getReceiptId()
    {
        return $this->receipt_id;
    }

    /**
     * The receipt identifier included in the request.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiptId($var)
    {
        GPBUtil::checkUint64($var);
        $this->receipt_id = $var;

        return $this;
    }

}

