<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The SendRequest message is used to send single updates or commands to the server.
 * Use within a RequestFrame. 
 *
 * Generated from protobuf message <code>stomp.SendRequest</code>
 */
class SendRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * A string that identifies the command destination.
     *
     * Generated from protobuf field <code>string destination = 1;</code>
     */
    private $destination = '';
    /**
     * A unique client-specific identifier for the send. 
     *
     * Generated from protobuf field <code>uint64 send_id = 2;</code>
     */
    private $send_id = 0;
    /**
     * The body to include in the send, if required.
     *
     * Generated from protobuf field <code>bytes body = 3;</code>
     */
    private $body = '';
    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 4;</code>
     */
    private $receipt_id = 0;

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * A string that identifies the command destination.
     *
     * Generated from protobuf field <code>string destination = 1;</code>
     * @return string
     */
    public function getDestination()
    {
        return $this->destination;
    }

    /**
     * A string that identifies the command destination.
     *
     * Generated from protobuf field <code>string destination = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setDestination($var)
    {
        GPBUtil::checkString($var, True);
        $this->destination = $var;

        return $this;
    }

    /**
     * A unique client-specific identifier for the send. 
     *
     * Generated from protobuf field <code>uint64 send_id = 2;</code>
     * @return int|string
     */
    public function getSendId()
    {
        return $this->send_id;
    }

    /**
     * A unique client-specific identifier for the send. 
     *
     * Generated from protobuf field <code>uint64 send_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSendId($var)
    {
        GPBUtil::checkUint64($var);
        $this->send_id = $var;

        return $this;
    }

    /**
     * The body to include in the send, if required.
     *
     * Generated from protobuf field <code>bytes body = 3;</code>
     * @return string
     */
    public function getBody()
    {
        return $this->body;
    }

    /**
     * The body to include in the send, if required.
     *
     * Generated from protobuf field <code>bytes body = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setBody($var)
    {
        GPBUtil::checkString($var, False);
        $this->body = $var;

        return $this;
    }

    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 4;</code>
     * @return int|string
     */
    public function getReceiptId()
    {
        return $this->receipt_id;
    }

    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 4;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiptId($var)
    {
        GPBUtil::checkUint64($var);
        $this->receipt_id = $var;

        return $this;
    }

}

