<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notifies a client of errors that occur at the server level. 
 *
 * Generated from protobuf message <code>stomp.ServerErrorResponse</code>
 */
class ServerErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 1;</code>
     */
    private $message = '';
    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 2;</code>
     */
    private $details = '';

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 2;</code>
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 2;</code>
     * @param string $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->details = $var;

        return $this;
    }

}

