<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Notifies a client of errors that occur for a specific subscription. 
 *
 * Generated from protobuf message <code>stomp.SubscriptionErrorResponse</code>
 */
class SubscriptionErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     */
    private $subscription_id = 0;
    /**
     * A unique identifier for this message.
     *
     * Generated from protobuf field <code>uint64 message_id = 2;</code>
     */
    private $message_id = 0;
    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     */
    private $message = '';
    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 4;</code>
     */
    private $details = '';

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     * @return int|string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * A unique identifier for this message.
     *
     * Generated from protobuf field <code>uint64 message_id = 2;</code>
     * @return int|string
     */
    public function getMessageId()
    {
        return $this->message_id;
    }

    /**
     * A unique identifier for this message.
     *
     * Generated from protobuf field <code>uint64 message_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setMessageId($var)
    {
        GPBUtil::checkUint64($var);
        $this->message_id = $var;

        return $this;
    }

    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @return string
     */
    public function getMessage()
    {
        return $this->message;
    }

    /**
     * Message that summarizes the error.
     *
     * Generated from protobuf field <code>string message = 3;</code>
     * @param string $var
     * @return $this
     */
    public function setMessage($var)
    {
        GPBUtil::checkString($var, True);
        $this->message = $var;

        return $this;
    }

    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 4;</code>
     * @return string
     */
    public function getDetails()
    {
        return $this->details;
    }

    /**
     * Detailed information about the error.
     *
     * Generated from protobuf field <code>string details = 4;</code>
     * @param string $var
     * @return $this
     */
    public function setDetails($var)
    {
        GPBUtil::checkString($var, True);
        $this->details = $var;

        return $this;
    }

}

