<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: stomp_v0.1.proto

namespace Stomp;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * The UnsubscribeRequest message is used to unsubscribe from a stream of events.
 * Use within a RequestFrame. 
 *
 * Generated from protobuf message <code>stomp.UnsubscribeRequest</code>
 */
class UnsubscribeRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     */
    private $subscription_id = 0;
    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 2;</code>
     */
    private $receipt_id = 0;

    public function __construct() {
        \GPBMetadata\StompV01::initOnce();
        parent::__construct();
    }

    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     * @return int|string
     */
    public function getSubscriptionId()
    {
        return $this->subscription_id;
    }

    /**
     * The client-specific subscription identifier.
     *
     * Generated from protobuf field <code>uint64 subscription_id = 1;</code>
     * @param int|string $var
     * @return $this
     */
    public function setSubscriptionId($var)
    {
        GPBUtil::checkUint64($var);
        $this->subscription_id = $var;

        return $this;
    }

    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 2;</code>
     * @return int|string
     */
    public function getReceiptId()
    {
        return $this->receipt_id;
    }

    /**
     * A unique (optional) receipt id to include if a receipt is desired.
     *
     * Generated from protobuf field <code>uint64 receipt_id = 2;</code>
     * @param int|string $var
     * @return $this
     */
    public function setReceiptId($var)
    {
        GPBUtil::checkUint64($var);
        $this->receipt_id = $var;

        return $this;
    }

}

